/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-06 11:40:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import party.model.vo.Party;
import java.util.ArrayList;
import java.util.Date;
import report.model.vo.Report;
import member.model.vo.Member;

public final class adminpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/admin/../common/header.jsp", Long.valueOf(1693993811403L));
    _jspx_dependants.put("/views/admin/../common/footer.jsp", Long.valueOf(1693893056761L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("report.model.vo.Report");
    _jspx_imports_classes.add("party.model.vo.Party");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    ArrayList<Party> partylist = (ArrayList<Party>) request.getAttribute("partylist");
    ArrayList<Member> memberlist = (ArrayList<Member>) request.getAttribute("memberlist");
    ArrayList<Report> reportlist = (ArrayList<Report>) request.getAttribute("reportlist");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/lib/jquery-ui.min.css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/comi/resources/css/main.css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/comi/resources/css/review.css\"/>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/common.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/comi/resources/js/question.js\"></script>\r\n");
      out.write(" 	<link rel=\"stylesheet\" href=\"/comi/resources/css/noticeView.css\"/> \r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 초기에는 모든 관리 페이지와 신고 항목을 숨깁니다. */\r\n");
      out.write("        .management-page {\r\n");
      out.write("        display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 선택된 관리 페이지를 표시합니다. */\r\n");
      out.write("        .management-page.active {   \r\n");
      out.write("        display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .report-section h4 {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 선택된 신고 항목을 표시합니다. */\r\n");
      out.write("        .report-section h4.active {\r\n");
      out.write("        display: block;\r\n");
      out.write("        }\r\n");
      out.write("             \r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("        // 라디오 버튼의 변경 이벤트를 감지하고 관리 페이지를 표시합니다.\r\n");
      out.write("            document.querySelectorAll('input[name=\"menu\"]').forEach(function(radio) {\r\n");
      out.write("                radio.addEventListener('change', function() {\r\n");
      out.write("                    var selectedMenu = this.value;\r\n");
      out.write("                    console.log(\"selectedMenu : \" + selectedMenu);\r\n");
      out.write("                // 선택한 관리 페이지만 표시합니다.\r\n");
      out.write("                    document.querySelectorAll('.management-page').forEach(function(page) {\r\n");
      out.write("                        page.classList.remove('active');\r\n");
      out.write("                    });\r\n");
      out.write("                document.querySelector('#' + selectedMenu + '-page').classList.add('active');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        function changeLogin(element){\r\n");
      out.write("            //radio 의 체크 상태가 변경된(change) input 태그의 name 속성값에서 userid 를 분리 추출함\r\n");
      out.write("            var usernum = element.name.substring(8);\r\n");
      out.write("            console.log(\"usernum : \" + usernum);\r\n");
      out.write("            \r\n");
      out.write("            if(element.checked == true && element.value == 'false'){\r\n");
      out.write("                //제한을 체크한 경우\r\n");
      out.write("                console.log(\"로그인 가능을 체크함\");\r\n");
      out.write("                location.href = \"/comi/loginok?usernum=\" + usernum + \"&ok=true\";\r\n");
      out.write("            }else{\r\n");
      out.write("                //가능을 체크한 경우\r\n");
      out.write("                console.log(\"로그인 제한을 체크함\");\r\n");
      out.write("                location.href = \"/comi/loginok?usernum=\" + usernum + \"&ok=false\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function changeParty(element){\r\n");
      out.write("            //radio 의 체크 상태가 변경된(change) input 태그의 name 속성값에서 userid 를 분리 추출함\r\n");
      out.write("            var panum = element.name.substring(14);\r\n");
      out.write("            var act = element.name.charAt(4);\r\n");
      out.write("            console.log(\"panum : \" + panum);\r\n");
      out.write("            console.log(\"act : \" + act);\r\n");
      out.write("            if(element.checked == true && element.value == 'false'){\r\n");
      out.write("                //제한을 체크한 경우\r\n");
      out.write("                console.log(\"모임 가능을 체크함\");\r\n");
      out.write("                location.href = \"/comi/partyban?panum=\" + panum + \"&ban=true&act=\" + act;\r\n");
      out.write("            }else{\r\n");
      out.write("                //가능을 체크한 경우\r\n");
      out.write("                console.log(\"모임 금지를 체크함\");\r\n");
      out.write("                location.href = \"/comi/partyban?panum=\" + panum + \"&ban=false&act=\" + act;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\" style=\"text-align: center;\">\r\n");
      out.write("    <header id=\"header_view\">\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');

	String type = (String) request.getAttribute("type");

      out.write('\r');
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	Member loginMember = (Member)session.getAttribute("loginMember");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>header</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/header.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header Section Begin -->\r\n");
      out.write("    \r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!--메뉴-->\r\n");
      out.write("            <nav class=\"header_menu\">\r\n");
      out.write("                <!--로고-->\r\n");
      out.write("                <div class=\"header_logo left\">\r\n");
      out.write("                    <a href=\"/comi/main.jsp\"><img src=\"/comi/resources/images/logo.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!--메뉴-->\r\n");
      out.write("                <div class=\"header_text center\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"");
      out.print( (type != null && type.equals("make")) ? "active" : "" );
      out.write("\"><a href=\"/comi/views/party/party_make.jsp\">공유 해요</a></li>\r\n");
      out.write("                        <li class=\"");
      out.print( (type != null && type.equals("findParty")) ? "active" : "" );
      out.write("\"><a href=\"/comi/partysall?type=findParty\">공유 찾기</a></li>\r\n");
      out.write("                        <li class=\"");
      out.print( (type != null && type.equals("findReview")) ? "active" : "" );
      out.write("\"><a href=\"/comi/partysall?type=findReview\">공유 후기</a></li>\r\n");
      out.write("                        <li class=\"");
      out.print( (type != null && type.equals("qna")) ? "active" : "" );
      out.write("\"><a href=\"/comi/qlist\">Q&A</a></li>\r\n");
      out.write("                        ");
 if (loginMember != null && "Y".equals(loginMember.getMeAdmin())) { 
      out.write("\r\n");
      out.write("                            <li class=\"");
      out.print( (type != null && type.equals("qna")) ? "active" : "" );
      out.write("\"><a href=\"/comi/admin\">Admin Page</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("				\r\n");
      out.write("                <!--장바구니, 찜-->\r\n");
      out.write("                <div class=\"header_right right\">\r\n");
      out.write("                    <div class=\"header_right_widget\">\r\n");
      out.write("                    	\r\n");
      out.write("                   		<!-- 비로그인 상태 -->\r\n");
      out.write("                    	");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("                    	 <a><img src=\"/comi/resources/images/launcher.png\" style=\"width: 30px; height: 30px\"></a>\r\n");
      out.write("                        <li><a href=\"/comi/views/member/member_login.html\">로그인</a></li>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 로그인 상태 -->\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <a href=\"/comi/myinfo?menum=");
      out.print( loginMember.getMeNum() );
      out.write("\">\r\n");
      out.write("                            ");
 if(loginMember.getMePhotoAdd() == null) { 
      out.write("\r\n");
      out.write("                                <img src=\"/comi/resources/images/launcher.png\" style=\"width: 30px; height: 30px\">\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <img src=\"/comi/resources/profile_photo_upfiles/");
      out.print( loginMember.getMeNum() );
      out.write('/');
      out.print( loginMember.getMePhotoAdd() );
      out.write("\" style=\"width: 30px; height: 30px\">\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"myinfo-box\">\r\n");
      out.write("                            <a href=\"/comi/myinfo?menum=");
      out.print( loginMember.getMeNum() );
      out.write('"');
      out.write('>');
      out.print( loginMember.getMeName() );
      out.write("님</a>\r\n");
      out.write("					        <a href=\"/comi/logout\">로그아웃</a> \r\n");
      out.write("                        </div>\r\n");
      out.write("					    ");
 } 
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Section End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- mobile_header 사용안함-->\r\n");
      out.write("    <header class=\"mobile_header\">\r\n");
      out.write("        \r\n");
      out.write("        <nav class=\"mobile_nav\">\r\n");
      out.write("            <div class=\"mobile_nav_top\">\r\n");
      out.write("                <a class=\"home_btn\" href=\"/comi/main.html\">\r\n");
      out.write("                    <img src=\"/comi/resources/images/headerTopIcon_1.png\" />\r\n");
      out.write("                </a>\r\n");
      out.write("            \r\n");
      out.write("                <button class=\"nav_btn\" type=\"button\">\r\n");
      out.write("                    <img src=\"/comi/resources/images/headerTopIcon_2.png\" />\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"navbar_box\">\r\n");
      out.write("                <div class=\"nav_item\">\r\n");
      out.write("                    <a class=\"nav_link\" href=\"/comi/views/party/party_make.html\" target=\"_blank\">\r\n");
      out.write("                        <img src=\"/comi/resources/images/headerSubIcon_1.png\" />\r\n");
      out.write("                            <span class=\"nav_link_tex\">공유 해요</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav_item\">\r\n");
      out.write("                    <a class=\"nav_link\" href=\"/comi/views/party/party_view.html\" target=\"_blank\">\r\n");
      out.write("                        <img src=\"/comi/resources/images/headerSubIcon_2.png\" />\r\n");
      out.write("                            <span class=\"nav_link_tex\">공유 찾기</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav_item\">\r\n");
      out.write("                    <a class=\"nav_link\" href=\"/comi/views/party/party_closed.html\" target=\"_blank\">\r\n");
      out.write("                        <img src=\"/comi/resources/images/headerSubIcon_3.png\" />\r\n");
      out.write("                            <span class=\"nav_link_tex\">공유 후기</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav_item\">\r\n");
      out.write("                    <a class=\"nav_link\" href=\"/comi/views/qna/qna.html\" target=\"_blank\">\r\n");
      out.write("                        <img src=\"/comi/resources/images/headerSubIcon_5.png\" />\r\n");
      out.write("                            <span class=\"nav_link_tex\">Q&A</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- mobile_header End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("     </header>\r\n");
      out.write("     <main>\r\n");
      out.write("        <div class=\"menu-select\">\r\n");
      out.write("            <input type=\"radio\" name=\"menu\" value=\"party\" checked> 파티 관리\r\n");
      out.write("            <input type=\"radio\" name=\"menu\" value=\"member\"> 회원 관리\r\n");
      out.write("            <input type=\"radio\" name=\"menu\" value=\"delete\"> 삭제 관리\r\n");
      out.write("            <input type=\"radio\" name=\"menu\" value=\"report\"> 신고 관리\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"management-page\" id=\"party-page\">\r\n");
      out.write("            <h3>파티 관리</h3>\r\n");
      out.write("    ");
 for(Party p : partylist){ 
      out.write("\r\n");
      out.write("        ");
      out.print( p.getPaTitle());
      out.write("\r\n");
      out.write("        ");
 if(p.getPaAct().equals("Y") || p.getPaAct().equals("N")){ 
      out.write("\r\n");
      out.write("            <input type=\"radio\" name=\"act_");
      out.print(p.getPaAct() );
      out.write("partyban_");
      out.print( p.getPaNum() );
      out.write("\" value=\"true\" \r\n");
      out.write("            onchange=\"changeParty(this);\" checked> 가능 &nbsp;\r\n");
      out.write("            <input type=\"radio\" name=\"act_");
      out.print(p.getPaAct() );
      out.write("partyban_");
      out.print( p.getPaNum() );
      out.write("\" value=\"false\" \r\n");
      out.write("            onchange=\"changeParty(this);\" > 금지<br>\r\n");
      out.write("        ");
 }else{ 
      out.write("\r\n");
      out.write("            <input type=\"radio\" name=\"act_");
      out.print(p.getPaAct() );
      out.write("partyban_");
      out.print( p.getPaNum() );
      out.write("\" value=\"true\" \r\n");
      out.write("            onchange=\"changeParty(this);\" > 가능 &nbsp;\r\n");
      out.write("            <input type=\"radio\" name=\"act_");
      out.print(p.getPaAct() );
      out.write("partyban_");
      out.print( p.getPaNum() );
      out.write("\" value=\"false\" \r\n");
      out.write("            onchange=\"changeParty(this);\" checked> 금지 <br>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"management-page\" id=\"member-page\">\r\n");
      out.write("        <h3>회원 관리</h3>\r\n");
      out.write("    ");
 for(Member m : memberlist){ 
      out.write("\r\n");
      out.write("        ");
      out.print( m.getMeName());
      out.write("\r\n");
      out.write("        ");
if( m.getMeLoginType().equals("N")){
      out.write("\r\n");
      out.write("            ");
if(m.getMeBan().equals("N")){ 
      out.write("\r\n");
      out.write("                <input type=\"radio\" name=\"loginok_");
      out.print( m.getMeNum() );
      out.write("\" value=\"true\" \r\n");
      out.write("                onchange=\"changeLogin(this);\" checked> 가능 &nbsp;\r\n");
      out.write("                <input type=\"radio\" name=\"loginok_");
      out.print( m.getMeNum() );
      out.write("\" value=\"false\" \r\n");
      out.write("                onchange=\"changeLogin(this);\" > 제한<br>\r\n");
      out.write("            ");
 }else{ 
      out.write("\r\n");
      out.write("                <input type=\"radio\" name=\"loginok_");
      out.print( m.getMeNum() );
      out.write("\" value=\"true\" \r\n");
      out.write("                onchange=\"changeLogin(this);\" > 가능 &nbsp;\r\n");
      out.write("                <input type=\"radio\" name=\"loginok_");
      out.print( m.getMeNum() );
      out.write("\" value=\"false\" \r\n");
      out.write("                onchange=\"changeLogin(this);\" checked> 제한<br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"management-page\" id=\"delete-page\">\r\n");
      out.write("        <h3>삭제 관리</h3>\r\n");
      out.write("        <h2>");
      out.print( memberlist.size());
      out.write("</h2>\r\n");
      out.write("        ");
 for(Member m : memberlist){ 
      out.write("\r\n");
      out.write("            ");
if( equals(m.getMeLoginType().equals("Y"))){
      out.write("\r\n");
      out.write("                ");
      out.print( m.getMeName());
      out.write(" &nbsp; \r\n");
      out.write("                ");

                Date currentDate = new Date(); // 현재 날짜
                Date modDate = m.getMeModDate(); // 회원 수정 날짜
                
                // 두 날짜의 대소 관계를 확인하여 순서를 조정
                if (modDate.after(currentDate)) {
                    // modDate가 현재 날짜보다 미래의 날짜인 경우, 두 날짜를 바꿔줍니다.
                    Date temp = currentDate;
                    currentDate = modDate;
                    modDate = temp;
                }
                
                long timeDifferenceMillis = currentDate.getTime() - modDate.getTime();
                long daysDifference = Math.abs(timeDifferenceMillis / (1000 * 60 * 60 * 24)); // 음수를 양수로 변환하여 일로 변환
                out.print("&nbsp;" + daysDifference + "일");

                
      out.write("\r\n");
      out.write("                ");
if(daysDifference > 10){ 
      out.write("\r\n");
      out.write("                    <h4>완전삭제</h4>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"management-page\" id=\"report-page\">\r\n");
      out.write("        <h3>신고 관리</h3>\r\n");
      out.write("        <h4>회원 신고</h4>\r\n");
      out.write("        ");
 for(Report r : reportlist){ 
      out.write("\r\n");
      out.write("            ");
if(r.getRpType().equals("member")){
      out.write("\r\n");
      out.write("                ");
      out.print( r.getRpNum());
      out.write("<br>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        <h4>파티 신고</h4>\r\n");
      out.write("        ");
 for(Report r : reportlist){ 
      out.write("\r\n");
      out.write("            ");
if(r.getRpType().equals("party")){
      out.write("\r\n");
      out.write("                ");
      out.print( r.getRpNum());
      out.write("<br>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        <h4>댓글 신고</h4>\r\n");
      out.write("        ");
 for(Report r : reportlist){ 
      out.write("\r\n");
      out.write("            ");
if(r.getRpType().equals("com")){
      out.write("\r\n");
      out.write("                ");
      out.print( r.getRpNum());
      out.write("<br>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        <h4>광고 신고</h4>\r\n");
      out.write("        ");
 for(Report r : reportlist){ 
      out.write("\r\n");
      out.write("            ");
if(r.getRpType().equals("adver")){
      out.write("\r\n");
      out.write("                ");
      out.print( r.getRpNum());
      out.write("<br>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</main>\r\n");
      out.write("    <footer id=\"footer_view\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>footer</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/comi/resources/css/footer.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Footer Section Begin -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container side_margin_zero\">\r\n");
      out.write("            <div class=\"footer_section_box\">\r\n");
      out.write("                <div class=\"footer_section\">\r\n");
      out.write("                    <div class=\"footer_div\">\r\n");
      out.write("                        <img src=\"/comi/resources/images/logo.png\" class=\"footer_logo\">\r\n");
      out.write("                        <div class=\"footer_right\">\r\n");
      out.write("                            <div class=\"footer_right_sub\">\r\n");
      out.write("                                <label class=\"footer_right_sub_label\">서비스</label>\r\n");
      out.write("                                <div class=\"footer_right_subsub\">\r\n");
      out.write("                                    <span class=\"footer_right_sub_text\"><a href=\"/comi/noticesall\">공지사항</a></span>\r\n");
      out.write("                                    <span class=\"footer_right_sub_text\">고객센터</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"footer_right_sub\">\r\n");
      out.write("                                <label class=\"footer_right_sub_label\">문의</label>\r\n");
      out.write("                                <div class=\"footer_right_subsub\">\r\n");
      out.write("                                    <span class=\"footer_right_sub_text\"><a href=\"/comi/blist\">사업 제휴</a></span>\r\n");
      out.write("                                    <span class=\"footer_right_sub_text\"><a href=\"/comi/adsall\">광고 문의</a></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"footer_bottom_1\">\r\n");
      out.write("                        <label class=\"footer_text_2\"><b>(주)십시일반</b></label>\r\n");
      out.write("                        <div class=\"\">\r\n");
      out.write("                            <p class=\"footer_text_2\">\r\n");
      out.write("                                <span>사업자 등록번호 : 없음</span> |<span> 팀장 : 김정선 </span>| 팀원 : 전성훤, 이재민, 나정운, 서진우 | <br>서울특별시 서초구 서초대로77길 41, 4층 (서초동, 대동Ⅱ)\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer_bottom_2\">\r\n");
      out.write("                        <span class=\"footer_text_1\">서비스 이용약관</span>\r\n");
      out.write("                        <span class=\"footer_text_1\">개인정보 처리방침</span>\r\n");
      out.write("                        <span class=\"footer_text_1 footer_copyright_text\">Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"#\" target=\"_blank\" class=\"team_text\">Comi</a></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- 상담 -->\r\n");
      out.write("    <div>\r\n");
      out.write("        <div class=\"launcher_character\">\r\n");
      out.write("            <button id=\"launcher_btn\" type=\"button\" class=\"\">\r\n");
      out.write("                <span class=\"text_hidden\">상담 버튼</span>\r\n");
      out.write("                <img alt=\"\" src=\"/comi/resources/images/launcher.png\" width=\"64\" height=\"64\" class=\"character_img\">\r\n");
      out.write("                <div class=\"hidden_message\">\r\n");
      out.write("                    <span class=\"\">0개의 안읽은 메시지</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 상담 End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("   \r\n");
      out.write("     </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
